release:

before:
  hooks:
    - go mod tidy

builds:
- id: kubectl-secret-data
  binary: kubectl-secret-data
  ldflags:
    - -s -w
    - -X main.Version={{.Version}}
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - arm64
    - amd64
    - ppc64le

archives:
- builds:
  - kubectl-secret-data
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
