name: test
on:
  push:
    branches:
      - "main"
  pull_request: {}
jobs:
  test:
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
      - name: test
        run: go test -v ./...
